import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/.next/**',
      '**/dist/**',
      '**/generated/**',
      'packages/db/prisma/migrations/**',
      // Generated by Next on every build; not ours to lint.
      'apps/web/next-env.d.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  prettier,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      'no-restricted-syntax': [
        'error',
        {
          // Time must be injectable so overdue/renewal maths is testable.
          selector: 'NewExpression[callee.name="Date"][arguments.length=0]',
          message: 'new Date() is banned - use clock.now() from @partners/core.',
        },
      ],
    },
  },
  {
    // The clock itself; and the seed, whose job is placing follow-up dates
    // relative to the real wall clock.
    files: ['packages/core/src/clock.ts', 'packages/db/prisma/seed.ts'],
    rules: { 'no-restricted-syntax': 'off' },
  },
  {
    files: ['apps/web/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: '@prisma/client',
              message: 'Import from @partners/db - only packages/db may construct a PrismaClient.',
            },
          ],
        },
      ],
    },
  },
);
